// vue-frontend-demo/src/components/demo-progress-bar.vue
<script setup lang="ts">
import { useDemoProgressBar } from '../composables/useDemoProgressBar/useDemoProgressBar';

const { current, max } = useDemoProgressBar();
</script>

<template>
  <progress :max="max" :value="current" />
  <span>Current progress is {{ current }} of {{ max }}</span>
</template>

<style lang="scss" scoped></style>

// nextjs-frontend-demo/app/ui/components/demo-progressbar.tsx
'use client';

import { useDemoProgressBar } from '../../hooks/useDemoProgressBar';

export const DemoProgressBar = () => {
  const progressBarState = useDemoProgressBar();

  if (!progressBarState) {
    return <span>Progress bar did not yet start</span>;
  }

  return (
    <>
      <progress max={progressBarState.max} value={progressBarState.current} />
      current progress is {progressBarState.current} on {progressBarState.max}
    </>
  );
};
